### ISSUE TITLE
Add general purpose unit test lib, and use it to test the functions in the library

### ISSUE THREAD

**Issue by mindfilleter** [sparr/pico8lib#5]
@sparr,

Firstly, thank you for merging #4! I'm happy to be able to contribute to your project as I find it very useful.

I've been tossing around the idea of implementing a light-weight unit test system to use in my games. the "[try](https://github.com/mindfilleter/pico8lib/blob/feature-test/functions.p8#L58)" function provided in functions.p8 is perfect for this. I took some time today to whip together a working prototype. I'd love to get your early feedback before I spend more time on this as I'd like to get this merged into pico8lib and used for pico8lib itself.

Here are some of my guiding thoughts for this:

1. It should be simple but not at the expense of readability
2. It's targeted more for advanced users, people who use #include and are comfortable running pico8 headless
3. It should include a minimal subset of features but be extensible (thank you class function)
4. Users *should not* put their test cases in their game source but instead make a separate cart (or carts if the token limit is reached) to host and run the tests

https://github.com/mindfilleter/pico8lib/blob/feature-test/test.p8

Here is a sample output from running this on test/test_test.p8. I included 1 intentional failure.

```bash
$ pico8 -x tests/test_test.p8
RUNNING: tests/test_test.p8
2023-4-16 23:50:49 INF - Running tests in suite test.p8
2023-4-16 23:50:49 INF - TestCase:assertions:test_assert_nil_pass ... PASS
2023-4-16 23:50:49 INF - TestCase:assertions:test_assert_not_nil_fail ... PASS
2023-4-16 23:50:49 ERR - assertions:test_assert_not_nil_pass [nil] is unexpectedly nil
2023-4-16 23:50:49 INF - TestCase:assertions:test_assert_nil_fail ... PASS
2023-4-16 23:50:49 INF - Finished suite: Ran 4 with 1 failure(s)
```

**Comment by sparr** [comment]
I like this idea. Having tests in a separate test cart is brilliant. I love that you're using the test library to test itself.
If we were to merge something like this, I might want to replace all the assert-based testing in the existing libraries with separate test files for each of them.
I do find the implementation a tad hard to read, but most class systems and uses in Lua usually are.

**Comment by mindfilleter** [comment]
I'll see what I can do to improve readability of the implementation. I'd be happy to help test the existing libraries as well. Thanks for the feedback. I'll keep working on this.

**Comment by mindfilleter** [comment]
Just pinging on this. I'm still working on the unit testing library. I've been busy with work stuff. I should have an update to the code ready this weekend.
