### ISSUE TITLE
.p8 extension not supported by luadoc or ldoc

### ISSUE THREAD

**Issue by mindfilleter** [sparr/pico8lib#7]
I spent some time today testing generating documentation from the comments using luadoc and ldoc. Luadoc worked the best but I found that it does not work with the .p8 file extension. It just ignores the files, even if you give exact paths for them.

I found that if you rename the files to *.p8.lua (i.e. test.p8.lua) then it works just fine and the output looks good.

My suggestion is to rename all of the files to .p8.lua

As for publishing the documentation, I think the best bet would be to write a markdown template for luadoc (or find one) so that we can publish the documentation in this repository's wiki. I'd be willing to help out with that.

![luadoc-example](https://github.com/sparr/pico8lib/assets/130892072/a405bb57-82f5-4200-99cf-e22c8e74c248)

**Comment by mindfilleter** [comment]
If you agree, I will setup a PR for this after we finish merging the unit test library.

**Comment by sparr** [comment]
I'd like to further explore getting ldoc to read the files without changing the name.
A markdown template seems like a good idea, both for the wiki and possibly also for a smaller reference directly in the repo.

**Comment by mindfilleter** [comment]
I'll dig into luadoc a little more and see if I missed something in my initial investigation.

**Comment by mindfilleter** [comment]
Okay, turns out you can add extensions. See [Extension modules written in C](https://github.com/lunarmodules/ldoc/wiki#extension-modules-written-in-c)

_An unknown extension can be associated with a language using a call like add_language_extension('lc','c') in config.ld. (Currently the language can only be 'c' or 'lua'.)_

So we should be able to just create config.ld and add this line to it:
```add_language_extension('p8','lua')```

It's strange to me that they didn't include this as a command line argument, or that they care to check file extensions at all instead of just taking a star pattern or regexp for files to process. Would have been like two switches. _--files **/*.p8 --lang lua_

Oh well. I'll close this issue and submit a PR with config.ld.
